// generated by go run gen-fonts.go; DO NOT EDIT

// Package xoloniumbold provides the "Xolonium Bold" TrueType font
// from the Xolonium font family.
package xoloniumbold // import "github.com/go-fonts/xonolonium/xoloniumbold"

import _ "embed"

// TTF is the data for the "Xolonium Bold" TrueType font.
//
//go:embed Xolonium-Bold.ttf
var TTF []byte
