// generated by go run gen-fonts.go; DO NOT EDIT

// Package xoloniumregular provides the "Xolonium Regular" TrueType font
// from the Xolonium font family.
package xoloniumregular // import "github.com/go-fonts/xonolonium/xoloniumregular"

import _ "embed"

// TTF is the data for the "Xolonium Regular" TrueType font.
//
//go:embed Xolonium-Regular.ttf
var TTF []byte
